---
title: "Tips and Tricks"
author: "Akis"
date: "19/01/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Save time when typing errors!

In many programming environments, the up arrow will cycle through previous commands.

# Can't remember variable names

Let's pretend you'd like to view the contents of a variable that you created earlier, but you can't seem to remember if you named it my_div or myDiv. You can type the first two letters of the variable name, then hit the Tab key (possibly more than once).

# View all objects in your workspace, working directory

* workspace - `ls()`
* working directory - `list.files()` or `dir()`

# What arguments can a function take?

`args()` - function goes inside parenthesis as in args(list.files)

# Working in directories

## Save your current working directory

mywd <- getwd()

Now when you move to another directory you can return to your original one using setwd(mywd)

## Create a directory in the current working directory
`dir.create()` - name of new directory goes inside parenthesis as in dir.create("testdir")

## Create a file in your working directory
`file.create()` - as in file.create("mytest.R")

## Check if a certain file exists in your current working directory
`file.exists()` - as in file.exists("mytest.R")

## Access information about a file in your current directory

`file.info()` - as in file.info("mytest.R")
You can use the `$` operator --- e.g., `file.info("mytest.R")$mode` --- to grab specific items.

## Change file names inside your current directory

`file.rename()` - as in file.rename("mytest.R", "mytest2.R") 

## Delete files in your current working directory
`file.remove()` - as in file.remove("mytest.R")

## Copy files in your current working directory

`file.copy()` - as in file.copy("mytest2.R", "mytest3.R")

## Provide the relative path to a file

`file.path()` - as in file.path("mytest3.R")

You can use file.path to construct file and directory paths that are independent of the operating system your R
code is running on. Pass 'folder1' and 'folder2' as arguments to file.path to make a platform-independent pathname. For example: `file.path("folder1", "folder2")`

## Create nested directories

Take a look at the documentation for dir.create by entering ?dir.create. Notice the 'recursive' argument. In
order to create nested directories, 'recursive' must be set to TRUE. Create a directory in the current working directory called "testdir2" and a subdirectory for it called "testdir3", all in one command by using dir.create() and file.path().

`dir.create(file.path("testdir2", "testdir3"), recursive = TRUE)`
